#!/usr/bin/ruby
require "erb"

errors = []
@files = Dir["html_tests/*/*html.go"].map do |f|
    base_name = File.basename(f.gsub("/","_")).split(".").first
    @wasm_name = "#{Time.now.to_i.to_s}_#{base_name}.wasm"
    errors.push `GOOS=js GOARCH=wasm go build -o public/#{@wasm_name} #{f}`
    file_name ="#{base_name}.html"
    f = File.open("./public/#{file_name}", "w+")
    f.write(ERB.new(File.read("./scripts/template.html.erb")).result(binding))
    f.close
    file_name
end

unless errors.reject(&:empty?).empty?
    raise Exception.new(errors.join("\n"))
end

f = File.open("./public/test_index.html", "w+")
f.write(ERB.new(File.read("./scripts/list_template.html.erb")).result(binding))

